### ISSUE TITLE
JournalEntryItem debit and credit is mutable

### ISSUE THREAD

**Issue by itiannerona** [maratmuginov/Pacioli#6]
This issue is related to issue #3 . Right now, the properties Debits and Credits of a journal item is mutable.

When a Journal is used in a client code, it shouldn't let its JournalEntry's Debit and Credit be edited, replaced, and deleted easily by the client code. Journal should have control over its properties.

**Comment by maratmuginov** [comment]
I believe we can solve this by making a journal item a `readonly struct` with `init` setters for all of its properties.
